### ISSUE TITLE
Missing on aur

### ISSUE THREAD

**Issue by aleray** [adityam/context-pkgbuild#2]
Hi,

the package is not referenced anymore on aur.archlinux.org. Is the packaged orphaned? Any alternative?

Thanks

**Comment by adityam** [comment]
This is not orphaned. I'll see why it is not referenced anymore.

**Comment by adityam** [comment]
The package is available on AUR again. I had missed the change in AUR. Thanks for reporting.

**Comment by aleray** [comment]
thanks!
